# Generated by Django 3.2.2 on 2021-05-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=200)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_message', models.CharField(max_length=200)),
                ('receive_time', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'ordering': ['receive_time'],
            },
        ),
    ]
