# Generated by Django 3.2.2 on 2021-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20210514_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(max_length=200),
        ),
    ]
