# Generated by Django 3.2.2 on 2021-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_email_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.CharField(max_length=200),
        ),
    ]
