# Generated by Django 3.2.2 on 2021-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20210515_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.CharField(max_length=200),
        ),
    ]
