# Generated by Django 3.2.2 on 2021-05-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('emails', '0007_auto_20210515_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
