# Generated by Django 3.2.2 on 2021-05-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_contact_email'),
        ('emails', '0008_auto_20210516_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='contact_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.EmailField(max_length=200),
        ),
    ]
