# Generated by Django 3.2.2 on 2021-05-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_contact_email'),
        ('emails', '0009_auto_20210517_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contact_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
