# Generated by Django 3.2.2 on 2021-05-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_contact_email'),
        ('emails', '0010_alter_email_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
