# Generated by Django 3.2.2 on 2021-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_adress', models.CharField(blank=True, max_length=255)),
                ('company_zip_code', models.CharField(blank=True, max_length=100)),
                ('company_city', models.CharField(blank=True, max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('company_notes', models.TextField(blank=True, null=True)),
                ('company_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
