# Generated by Django 3.2.2 on 2021-05-12 09:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=255)),
                ('contact_last_name', models.CharField(max_length=255)),
                ('contact_job', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('contact_notes', models.TextField(blank=True, null=True)),
                ('contact_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['contact_last_name'],
            },
        ),
    ]
