# Generated by Django 3.2.2 on 2021-05-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_crm', '0004_auto_20210512_0902'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_crm.company'),
            preserve_default=False,
        ),
    ]
