# Generated by Django 3.2.2 on 2021-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
