# Generated by Django 3.2.2 on 2021-05-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_contact_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_company',
        ),
    ]
