# Generated by Django 3.2.2 on 2021-05-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_crm', '0004_auto_20210512_0902'),
        ('contacts', '0003_remove_contact_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_crm.company'),
        ),
    ]
