# Generated by Django 3.2.2 on 2021-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210516_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
