# Generated by Django 3.2.2 on 2021-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_contact_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
