# Generated by Django 3.2.2 on 2021-05-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0007_auto_20210513_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
