# Generated by Django 3.2.2 on 2021-05-11 14:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_adress', models.CharField(blank=True, max_length=255)),
                ('company_zip_code', models.IntegerField(blank=True)),
                ('company_city', models.CharField(blank=True, max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('company_notes', models.TextField(blank=True, null=True)),
                ('company_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=255)),
                ('contact_last_name', models.CharField(max_length=255)),
                ('contact_job', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('contact_notes', models.TextField(blank=True, null=True)),
                ('contact_created_on', models.DateTimeField(auto_now_add=True)),
                ('contact_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_crm.company')),
            ],
            options={
                'ordering': ['contact_last_name'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=200)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_message', models.CharField(max_length=200)),
                ('receive_time', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_crm.contact')),
            ],
            options={
                'ordering': ['receive_time'],
            },
        ),
    ]
