# Generated by Django 3.2.2 on 2021-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crm', '0002_alter_company_company_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
