# Generated by Django 3.2.2 on 2021-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_crm', '0003_alter_company_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='from_email',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
